### ISSUE TITLE
Improve KEYFILE regex

### ISSUE THREAD

**Issue by abilioesteves** [labbsr0x/bindman-dns-bind9#14]
The regex applied to the KEYFILE param restricts the usage of Bindman to other Bind9 setups in regards to the Key generation algorithm.

If one would generate a Key with the following perfectly fine example, he/she would not be able to use Bindman:

```bash
dnssec-keygen -a DSA -b 768 -n ZONE test.com
```

Since, as result of this command, the key files generated would be:

```
Ktest.com.+003+06286.key
Ktest.com.+003+06286.private
```

Which, at the current implementation, are denied as valid key files.

**Comment by werberson** [comment]
I think it is not interesting to the Bindman to validate the key name pattern.

The user can inform the file name he wants and the Bindman just validates if the name isn't empty and the file exists.

**Comment by abilioesteves** [comment]
Agreed.
